### ISSUE TITLE
Issue on installation

### ISSUE THREAD

**Issue by Startx04** [andriusr/OpenQuotesAndContracts#4]
I have issues installing the module.

```
SugarCRM is Version 6.5.20 (Build 1001)
AjaxUI turned off
```

When i upload the zip file in the module loader i get following message:
ZIP Error(0): Status(0): Arhive(upload://OpenQuotesAndContracts-fc493ea6263939106f9b0d7f872da842560d1358.zip): Directory(/usr/www/users///cache/upgrades/temp/kmDGrd)

And thats it. It does not open the install routine or anything else. Folder permission is on 775. Strange is also that the folder in the temp appears empty when accessing via ftp.

Any idea what happens there?

**Comment by backin2shape** [comment]
i'm getting the same error, were you able to resolve this?  if so, how?

**Comment by andriusr** [comment]
The issue is in your Apache/PHP server configuration, it seems that zip files are not processed. PHP extension that handles zip files should be enabled.

**Comment by Startx04** [comment]
I had Wordpress on the same server installed and it was running fine. It also handles zip files for updates etc. without any issues.
But i have uninstalled the software since i have not enough knowledge to fit it for my needs nor the budget available to outsource it... Therefore i close the issue.
